

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";
export const GET_CATEGORIES_RESET = "GET_CATEGORIES_RESET";

export const ADMIN_DELETE_CATEGORIES_REQUEST = "ADMIN_DELETE_CATEGORIES_REQUEST";
export const ADMIN_DELETE_CATEGORIES_SUCCESS = "ADMIN_DELETE_CATEGORIES_SUCCESS";
export const ADMIN_DELETE_CATEGORIES_FAILURE = "ADMIN_DELETE_CATEGORIES_FAILURE";
export const ADMIN_DELETE_CATEGORIES_RESET = "ADMIN_DELETE_CATEGORIES_RESET";

export const ADMIN_CREATE_CATEGORIES_REQUEST = "ADMIN_CREATE_CATEGORIES_REQUEST";
export const ADMIN_CREATE_CATEGORIES_SUCCESS = "ADMIN_CREATE_CATEGORIES_SUCCESS";
export const ADMIN_CREATE_CATEGORIES_FAILURE = "ADMIN_CREATE_CATEGORIES_FAILURE";
export const ADMIN_CREATE_CATEGORIES_RESET = "ADMIN_CREATE_CATEGORIES_RESET";

export const ADMIN_UPDATE_CATEGORIES_REQUEST = "ADMIN_UPDATE_CATEGORIES_REQUEST";
export const ADMIN_UPDATE_CATEGORIES_SUCCESS = "ADMIN_UPDATE_CATEGORIES_SUCCESS";
export const ADMIN_UPDATE_CATEGORIES_FAILURE = "ADMIN_UPDATE_CATEGORIES_FAILURE";
export const ADMIN_UPDATE_CATEGORIES_RESET = "ADMIN_UPDATE_CATEGORIES_RESET";