export const GET_ALL_MOVIES_REQUEST = "GET_ALL_MOVIES_REQUEST";
export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS";
export const GET_ALL_MOVIES_FAILURE = "GET_ALL_MOVIES_FAILURE";
export const GET_ALL_MOVIES_RESET = "GET_ALL_MOVIES_RESET";

export const GET_DETAILS_MOVIE_REQUEST = "GET_DETAILS_MOVIE_REQUEST";
export const GET_DETAILS_MOVIE_SUCCESS = "GET_DETAILS_MOVIE_SUCCESS";
export const GET_DETAILS_MOVIE_FAILURE = "GET_DETAILS_MOVIE_FAILURE";
export const GET_DETAILS_MOVIE_RESET = "GET_DETAILS_MOVIE_RESET";

export const GET_TOP_RATE_MOVIE_REQUEST = "GET_TOP_RATE_MOVIE_REQUEST";
export const GET_TOP_RATE_MOVIE_SUCCESS = "GET_TOP_RATE_MOVIE_SUCCESS";
export const GET_TOP_RATE_MOVIE_FAILURE = "GET_TOP_RATE_MOVIE_FAILURE";
export const GET_TOP_RATE_MOVIE_RESET = "GET_TOP_RATE_MOVIE_RESET";

export const GET_RANDOM_MOVIE_REQUEST = "GET_RANDOM_MOVIE_REQUEST";
export const GET_RANDOM_MOVIE_SUCCESS = "GET_RANDOM_MOVIE_SUCCESS";
export const GET_RANDOM_MOVIE_FAILURE = "GET_RANDOM_MOVIE_FAILURE";
export const GET_RANDOM_MOVIE_RESET = "GET_RANDOM_MOVIE_RESET";