export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAILURE = "USER_UPDATE_PROFILE_FAILURE";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_CHANGE_PASSWORD_REQUEST = "USER_CHANGE_PASSWORD_REQUEST";
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS";
export const USER_CHANGE_PASSWORD_FAILURE = "USER_CHANGE_PASSWORD_FAILURE";
export const USER_CHANGE_PASSWORD_RESET = "USER_CHANGE_PASSWORD_RESET";

export const GET_FAVORITE_MOVIES_REQUEST = "GET_FAVORITE_MOVIES_REQUEST";
export const GET_FAVORITE_MOVIES_SUCCESS = "GET_FAVORITE_MOVIES_SUCCESS";
export const GET_FAVORITE_MOVIES_FAILURE = "GET_FAVORITE_MOVIES_FAILURE";
export const GET_FAVORITE_MOVIES_RESET = "GET_FAVORITE_MOVIES_RESET";

export const DELETE_FAVORITE_MOVIES_REQUEST = "DELETE_FAVORITE_MOVIES_REQUEST";
export const DELETE_FAVORITE_MOVIES_SUCCESS = "DELETE_FAVORITE_MOVIES_SUCCESS";
export const DELETE_FAVORITE_MOVIES_FAILURE = "DELETE_FAVORITE_MOVIES_FAILURE";
export const DELETE_FAVORITE_MOVIES_RESET = "DELETE_FAVORITE_MOVIES_RESET";


export const REVIEW_MOVIE_REQUEST = "REVIEW_MOVIE_REQUEST";
export const REVIEW_MOVIE_SUCCESS = "REVIEW_MOVIE_SUCCESS";
export const REVIEW_MOVIE_FAILURE = "REVIEW_MOVIE_FAILURE";
export const REVIEW_MOVIE_RESET = "REVIEW_MOVIE_RESET";


export const LIKE_MOVIE_REQUEST = "LIKE_MOVIE_REQUEST";
export const LIKE_MOVIE_SUCCESS = "LIKE_MOVIE_SUCCESS";
export const LIKE_MOVIE_FAILURE = "LIKE_MOVIE_FAILURE";
export const LIKE_MOVIE_RESET = "LIKE_MOVIE_RESET";